In [1]:
import numpy as np
import matplotlib.pyplot as plt

## x is number of hours a student is studying
## y is pass fail , pass as 1 and fail as o

In [40]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.array([0,0,0,0,1,1,1,1,1,1])

In [41]:
def sigmoid(z):
    
    output = 1 / (1 + np.exp(-z))
    
    return output

In [42]:
def loss(y , p):
    
    loss = - np.mean( y* np.log(p)      +    (1-y)  * np.log(1-p))
    return loss

In [45]:
b0 = 0
b1 = 0
alpha = 0.01 #learning
iteration = 1000
tol = 1e-6 #tolerance and number of iteration

In [46]:
cost = []

for i in range(iteration):
    
    z = b0 + b1 * x
    p = sigmoid(z)
    
    error = loss(y,p )
    cost.append(error)
    
    
    #gradient descent
    gard_err = p-y
    b0 = b0 - alpha* np.sum(gard_err)
    b1 = b1 - alpha * np.sum(gard_err * x)
    
    if i > 0  and abs( cost[-1] - cost[-2]) < tol:
        break
    
print("final bo", b0)
print("final b1", b1)

final bo -5.230062614614006
final b1 1.2291873309564059


In [51]:
from sklearn.linear_model import LogisticRegression

x = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(-1,1)
y = np.array([0,0,0,0,1,1,1,1,1,1])

model = LogisticRegression()
model.fit(x,y)



LogisticRegression()

In [52]:
model.intercept_

array([-5.30721006])

In [53]:
model.coef_

array([[1.18107562]])

In [49]:
abs(-10.82873333)

10.82873333

In [54]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
x.shape

(10,)

In [55]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
x = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(-1,1)
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [57]:
x.shape

(10, 1)